# Generated by Django 5.2.17 on 2026-09-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_code', models.CharField(max_length=50, unique=True)),
                ('sector', models.CharField(max_length=100)),
                ('washing_station', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1_plots', to='farmers.farmer')),
            ],
        ),
    ]
