# Generated by Django 5.2.17 on 2026-09-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washing_station', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('grade', models.CharField(max_length=5)),
                ('delivered_on', models.DateField()),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f1_deliveries', to='plots.plot')),
            ],
        ),
    ]
